services:
  grafana:
    build: .
    container_name: my_flask_app_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PROMETHEUS_URL: http://prometheus:9090
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - localprom

networks:
  localprom:
    external: true
    name: monitoring_localprom
