services:
  grafana:
    build: .
    container_name: my_flask_app_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PROMETHEUS_URL: https://streaming-search-prometheus-8b66711fac46.herokuapp.com
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - localprom

networks:
  localprom:
    external: true
    name: monitoring_localprom
