version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my_flask_app_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_app_network

networks:
  flask_app_network:
    name: flask_app_network

volumes:
  postgres_data:
