global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    scheme: https
    static_configs:
      - targets:
          - streaming-search-prometheus-8b66711fac46.herokuapp.com

  - job_name: streaming-search-app
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - streaming-search-app-373a9f8fa5f5.herokuapp.com
